### PR TITLE
Fix Dockerfile

### PR DESCRIPTION
**Pull request by abueide**
Fixes the Dockerfile by switching from default-jdk to AdoptOpenJDK's build of openjdk 8, and setting the JAVA8_HOME environment variable.

### CODE REVIEW

**Comment by ndkimhao** [comment]
This looks good! Thanks for fixing it.

**Comment by ndkimhao** [comment]
@abueide could you also push the lastest docker image to https://hub.docker.com/repository/docker/unsatx/dig ? I have added you to the org on Docker Hub.

**Comment by abueide** [comment]
@ndkimhao pushed the images, you can use unsatx/dig:latest or unsatx/dig:1.0.1 now

**Comment by abueide** [comment]
as an example, you can call this command and change ${currentFilePath} with a path to a c or java file and it will run dig on it.

docker run -v  ${currentFilePath}:${currentFilePath} unsatx/dig:latest /bin/bash -c 'sage -python -O dig.py ${currentFilePath} -log 3'

note docker doesn't like relative paths so you might have to do $(pwd)/someRelativePath/:/someRelativePath/ on linux or ${pwd}  in powershell

**Pull request merged**
